from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any
from uuid import UUID


class VersionStatus(StrEnum):
    CANDIDATE = "candidate"  # auto-triggered, awaiting proposal approval
    ACTIVE = "active"  # the live version for this agent
    ARCHIVED = "archived"  # superseded by a newer active version


class VersionTrigger(StrEnum):
    MANUAL = "manual"
    CONFIG_PATCH = "config_patch"
    SKILL_CREATED = "skill_created"
    EVAL_PASS = "eval_pass"
    RL_MUTATION = "rl_mutation"  # generated by GenomeEvolver / SkillBandit
    METACOG_FIX = "metacog_fix"  # proposed by metacognition node
    SKILL_TRAIN = "skill_train"  # accepted by ReflACT optimizer


class MutationType(StrEnum):
    PROMPT_REWRITE = "prompt_rewrite"
    SKILL_MUTATE = "skill_mutate"
    TOOL_TOGGLE = "tool_toggle"
    TEMPERATURE_SWEEP = "temperature_sweep"
    RL_UPDATE = "rl_update"


@dataclass
class ModelConfig:
    provider: str  # "openai" | "anthropic" | "ollama"
    model: str
    temperature: float
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentGenome:
    # Required (no defaults)
    agent_id: UUID
    version_label: str  # "v3" | "auto-skill-2026-05-08T03:00"
    template: str  # "deer_flow" | "linear-3" | "tool-agent"
    system_prompt: str  # first-class field
    llm_config: ModelConfig
    tools: dict[str, bool]  # {"retrieve": True, "sandbox": False, ...}
    status: VersionStatus
    trigger: VersionTrigger

    # Optional with factory defaults
    active_skill_ids: list[UUID] = field(default_factory=list)
    active_skill_names: list[str] = field(default_factory=list)  # denormalized for display

    # Optional with None defaults
    created_by: UUID | None = None
    created_at: datetime.datetime | None = None
    avg_score: float | None = None  # cached from last eval
    pass_rate: float | None = None
    proposal_id: UUID | None = None  # linked proposal (CANDIDATE only)
    id: UUID | None = None  # None until persisted

    # RL / lineage fields (Phase 0 — Flow v2)
    parent_id: UUID | None = None  # genome this was derived from
    generation: int = 0  # evolution generation counter
    mutation_type: str | None = None  # MutationType value or None
    reward_signal: float | None = None  # cumulative reward from RL loop
    metacog_snapshot: dict[str, Any] | None = None  # metacog state at snapshot time

    def to_jsonb_dict(self) -> dict:
        """Convert to JSON-safe dict for asyncpg JSONB storage."""
        return {
            "agent_id": str(self.agent_id),
            "version_label": self.version_label,
            "template": self.template,
            "system_prompt": self.system_prompt,
            "llm_config": {
                **self.llm_config.extra,
                "provider": self.llm_config.provider,
                "model": self.llm_config.model,
                "temperature": self.llm_config.temperature,
            },
            "tools": self.tools,
            "active_skill_ids": [str(sid) for sid in self.active_skill_ids],
            "active_skill_names": self.active_skill_names,
            "status": self.status.value,
            "trigger": self.trigger.value,
            "created_by": str(self.created_by) if self.created_by else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "avg_score": self.avg_score,
            "pass_rate": self.pass_rate,
            "proposal_id": str(self.proposal_id) if self.proposal_id else None,
            "id": str(self.id) if self.id else None,
            # RL / lineage
            "parent_id": str(self.parent_id) if self.parent_id else None,
            "generation": self.generation,
            "mutation_type": self.mutation_type,
            "reward_signal": self.reward_signal,
            "metacog_snapshot": self.metacog_snapshot,
        }

    @classmethod
    def from_row(cls, row: dict) -> AgentGenome:
        """Reconstruct from a DB row dict (asyncpg Record or plain dict)."""
        llm_raw = row.get("llm_config") or row.get("model_config") or {}
        return cls(
            id=UUID(str(row["id"])) if row.get("id") else None,
            agent_id=UUID(str(row["agent_id"])),
            version_label=row["version_label"],
            template=row.get("template", "deer_flow"),
            system_prompt=row.get("system_prompt", ""),
            llm_config=ModelConfig(
                provider=llm_raw.get("provider", "openai"),
                model=llm_raw.get("model", "gpt-5.4-mini"),
                temperature=float(llm_raw.get("temperature", 0.2)),
                extra={k: v for k, v in llm_raw.items() if k not in ("provider", "model", "temperature")},
            ),
            tools=row.get("tools", {}),
            active_skill_ids=[UUID(s) for s in (row.get("active_skill_ids") or [])],
            active_skill_names=row.get("active_skill_names") or [],
            status=VersionStatus(row.get("status", VersionStatus.ACTIVE)),
            trigger=VersionTrigger(row.get("trigger", VersionTrigger.MANUAL)),
            created_by=UUID(str(row["created_by"])) if row.get("created_by") else None,
            created_at=row.get("created_at"),
            avg_score=row.get("avg_score"),
            pass_rate=row.get("pass_rate"),
            proposal_id=UUID(str(row["proposal_id"])) if row.get("proposal_id") else None,
            # RL / lineage
            parent_id=UUID(str(row["parent_id"])) if row.get("parent_id") else None,
            generation=int(row.get("generation") or 0),
            mutation_type=row.get("mutation_type"),
            reward_signal=float(row["reward_signal"]) if row.get("reward_signal") is not None else None,
            metacog_snapshot=row.get("metacog_snapshot"),
        )
